# Generated by Django 2.2.4 on 2019-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_map', '0002_auto_20190806_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
