# Generated by Django 2.2.3 on 2019-08-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_map', '0003_catphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='catlist',
            name='family',
            field=models.BooleanField(default=False, verbose_name='가족이 있음'),
        ),
        migrations.AddField(
            model_name='catlist',
            name='food',
            field=models.BooleanField(default=False, verbose_name='주기적으로 급식을 먹고 있음'),
        ),
        migrations.AddField(
            model_name='catlist',
            name='furious',
            field=models.BooleanField(default=False, verbose_name='경계심이 많음'),
        ),
        migrations.AddField(
            model_name='catlist',
            name='health',
            field=models.BooleanField(default=False, verbose_name='정기적으로 병원을 다니고 있음'),
        ),
        migrations.AddField(
            model_name='catlist',
            name='marks',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='catlist',
            name='pos_x',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='catlist',
            name='pos_y',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='catlist',
            name='touch',
            field=models.BooleanField(default=False, verbose_name='만지면 안됨'),
        ),
        migrations.AddField(
            model_name='catphoto',
            name='catnum',
            field=models.IntegerField(default=-5),
        ),
        migrations.AddField(
            model_name='catphoto',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='catlist',
            name='age',
            field=models.CharField(choices=[('a', '아기묘'), ('b', '성묘'), ('c', '노묘'), ('d', '모름')], default='?', max_length=1),
        ),
        migrations.AlterField(
            model_name='catlist',
            name='gender',
            field=models.CharField(choices=[('0', '모름'), ('1', '남'), ('2', '여')], max_length=1),
        ),
        migrations.AlterField(
            model_name='catlist',
            name='info',
            field=models.TextField(default='a'),
        ),
    ]
