# Generated by Django 2.2.1 on 2019-05-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dongbang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('writter', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
