# Generated by Django 2.2.1 on 2019-05-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dongbang',
            old_name='writter',
            new_name='writer',
        ),
    ]
